### ISSUE TITLE
Busktäckning problem

### ISSUE THREAD

**Issue by hemip** [hemip/strand2018#2]
Har nu kollat att göra pull på projektet och kompilera lokalt på min Mac. Allt verkar fungera och jag får en körbar apk.

Kollade nya busktäckvariabeln. Upptäckte då en bug. När man lagt till ett nytt habitat och valt busktäckning och sparat och sedan går tillbaka in i 'habitatet' så visas inte den valda täckningen utan default-värdet 'ej aktuellt'.

/hans

**Comment by viktorroos** [comment]
Hmm, testade nyss själv och för mig stannar alla värdena kvar även om jag stänger av applikationen helt och startar upp igen. Gäller det enbart busktäckning eller får du samma problem med krontäckning, död ved, finns träd och finns stubbar?

**Comment by hemip** [comment]
Det är nya busktäckning under habitat

**Comment by viktorroos** [comment]
Jo men hur ser det ut med dom andra fälten som är nya? Det finns ju 5 nya fält under habitat numera. Är det samma problem med samtliga fält? (alltså att värdena inte sparas)

**Comment by hemip** [comment]
Jag kollar...

**Comment by hemip** [comment]
Har kompilerat uppdaterad version med flera nya variabler och allt ser OK ut. Variablerna exporteras också.
